<?xml version="1.0" encoding="utf-8"?><Database Name="social" Class="EntitiesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\social.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="socialConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Album" Member="Albums">
    <Type Name="Album">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_Album_aspnet_Photo" Member="Photos" ThisKey="Id" OtherKey="AlbumId" Type="Photo" />
      <Association Name="aspnet_Object_aspnet_Album" Member="Object" ThisKey="Id" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Album" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Article" Member="Articles">
    <Type Name="Article">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Comment" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_Object_aspnet_Comment" Member="aspnet_Object" ThisKey="Id" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="aspnet_Object_aspnet_Comment1" Member="Object" ThisKey="ObjectId" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Comment" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Developer" Member="Developers">
    <Type Name="Developer">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApiKey" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Developer" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_FriendGroup" Member="FriendGroups">
    <Type Name="FriendGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_FriendGroup_aspnet_FriendGroupFriendship" Member="FriendGroupFriendships" ThisKey="Id" OtherKey="FriendGroupId" Type="FriendGroupFriendship" />
      <Association Name="aspnet_User_aspnet_FriendGroup" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_FriendGroupFriendship" Member="FriendGroupFriendships">
    <Type Name="FriendGroupFriendship">
      <Column Name="FriendshipId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FriendGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="aspnet_FriendGroup_aspnet_FriendGroupFriendship" Member="FriendGroup" ThisKey="FriendGroupId" OtherKey="Id" Type="FriendGroup" IsForeignKey="true" />
      <Association Name="aspnet_Friendship_aspnet_FriendGroupFriendship" Member="Friendship" ThisKey="FriendshipId" OtherKey="Id" Type="Friendship" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Friendship" Member="Friendships">
    <Type Name="Friendship">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="FriendId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_Friendship_aspnet_FriendGroupFriendship" Member="FriendGroupFriendships" ThisKey="Id" OtherKey="FriendshipId" Type="FriendGroupFriendship" />
      <Association Name="aspnet_User_aspnet_Friendship" Member="aspnet_User" ThisKey="FriendId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Friendship1" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="Memberships">
    <Type Name="Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_User_aspnet_Membership" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Object" Member="Objects">
    <Type Name="Object">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Object_aspnet_Album" Member="Album" ThisKey="Id" OtherKey="Id" Type="Album" Cardinality="One" />
      <Association Name="aspnet_Object_aspnet_Comment" Member="aspnet_Comment" ThisKey="Id" OtherKey="Id" Type="Comment" Cardinality="One" />
      <Association Name="aspnet_Object_aspnet_Comment1" Member="Comments" ThisKey="Id" OtherKey="ObjectId" Type="Comment" />
      <Association Name="aspnet_Object_aspnet_Photo" Member="Photo" ThisKey="Id" OtherKey="Id" Type="Photo" Cardinality="One" />
      <Association Name="aspnet_Object_aspnet_Post" Member="Post" ThisKey="Id" OtherKey="Id" Type="Post" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Photo" Member="Photos">
    <Type Name="Photo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AlbumId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Caption" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_Album_aspnet_Photo" Member="Album" ThisKey="AlbumId" OtherKey="Id" Type="Album" IsForeignKey="true" />
      <Association Name="aspnet_Object_aspnet_Photo" Member="Object" ThisKey="Id" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Photo" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Post" Member="Posts">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_Object_aspnet_Post" Member="Object" ThisKey="Id" OtherKey="Id" Type="Object" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Post" Member="aspnet_User" ThisKey="PersonId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="aspnet_User_aspnet_Post1" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Profile" Member="Profiles">
    <Type Name="Profile">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PropertyNames" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesString" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PropertyValuesBinary" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastUpdatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Profile" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UserConfirmation" Member="UserConfirmations">
    <Type Name="UserConfirmation">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="aspnet_User_aspnet_UserConfirmation" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UserPrivacy" Member="UserPrivacies">
    <Type Name="UserPrivacy">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Key]" Member="Key" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_User_aspnet_UserPrivacy" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="Users">
    <Type Name="User">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_User_aspnet_Album" Member="Albums" ThisKey="UserId" OtherKey="UserId" Type="Album" />
      <Association Name="aspnet_User_aspnet_Comment" Member="Comments" ThisKey="UserId" OtherKey="UserId" Type="Comment" />
      <Association Name="aspnet_User_aspnet_Developer" Member="Developer" ThisKey="UserId" OtherKey="UserId" Type="Developer" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_FriendGroup" Member="FriendGroups" ThisKey="UserId" OtherKey="UserId" Type="FriendGroup" />
      <Association Name="aspnet_User_aspnet_Friendship" Member="aspnet_Friendships" ThisKey="UserId" OtherKey="FriendId" Type="Friendship" />
      <Association Name="aspnet_User_aspnet_Friendship1" Member="Friendships" ThisKey="UserId" OtherKey="UserId" Type="Friendship" />
      <Association Name="aspnet_User_aspnet_Membership" Member="Membership" ThisKey="UserId" OtherKey="UserId" Type="Membership" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_Photo" Member="Photos" ThisKey="UserId" OtherKey="UserId" Type="Photo" />
      <Association Name="aspnet_User_aspnet_Post" Member="aspnet_Posts" ThisKey="UserId" OtherKey="PersonId" Type="Post" />
      <Association Name="aspnet_User_aspnet_Post1" Member="Posts" ThisKey="UserId" OtherKey="UserId" Type="Post" />
      <Association Name="aspnet_User_aspnet_Profile" Member="Profile" ThisKey="UserId" OtherKey="UserId" Type="Profile" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UserConfirmation" Member="UserConfirmation" ThisKey="UserId" OtherKey="UserId" Type="UserConfirmation" Cardinality="One" />
      <Association Name="aspnet_User_aspnet_UserPrivacy" Member="UserPrivacies" ThisKey="UserId" OtherKey="UserId" Type="UserPrivacy" />
    </Type>
  </Table>
</Database>